# buildspec_deploy.yml
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - yum install -y git
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Building the static site..."
      - npm run build
  post_build:
    commands:
      - echo "Creating deployment package from 'dist' directory..."
      - cd dist/ && zip -r ../deployment-package.zip .

      # Upload the pacakge to versioned artifacts bucket
      - echo "Uploading artifact to S3..."
      - UPLOAD_OUTPUT=$(aws s3api put-object --bucket $ARTIFACTS_BUCKET --key frontend/deployment-package.zip --body ../deployment-package.zip)

      # Extract the unqiue version ID
      - VERSION_ID=$(echo $UPLOAD_OUTPUT | jq -r .VersionId)
      - echo "New Version ID is ${VERSION_ID}"
      - GIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - COMMIT_MSG=$(git log -1 --pretty=%B | tr -d '\n' | jq -sR)

      - |
        PARAM_VALUE=$(cat <<EOF
        {
          "s3VersionId": "$VERSION_ID",
          "commitHash": "$GIT_HASH",
          "commitMessage": $COMMIT_MSG
        }
        EOF
        )

      # New: Save the VersionId to SSM
      - 'echo "Storing deployment info in SSM: ${PARAM_VALUE}"'
      - 'aws ssm put-parameter --name "/MyApp/Frontend/LatestVersionID" --value "${PARAM_VALUE}" --type "String" --overwrite'

artifacts:
  # The output of this stage is everything in the 'dist' folder
  base-directory: dist
  files:
    - '**/*'